# Generated by Django 4.2.4 on 2023-08-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_description',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
